let langs = [
  "HTML",
  "HTML5",
  "CSS",
  "CSS3",
  "SASS",
  "Bootstrap",
  "Materialize",
  "Javascript",
  "JS DOM",
  "JS BOM",
  "ES6, ES7, ES8, ES9",
  "Angular",
  "RXJS",
  "React",
  "REDUX",
  "VUE",
  "VUEX",
  "GraphQL, Express GraphQL",
  "GraphQL Yoga",
  "Apollo Client",
  "Express",
  "NodeJS",
  "MongoDB",
  "POSTGRES",
  "MYSQL",
  "ORM [Mongoose, Sequlelze]",
  "REDIS",
  "Electron",
  "React Native",
  "Socket[ Server - Client ]",
  "DS - AL",
  "Functional Programming",
  "OOP Programming",
  "DOCKER",
  "kubernetes",
  "AWS",
  "NGINX",
  "Typescript",
  "AJAX",
  "Webpack",
  "Babel",
  "Server Side Rendering",
  "Templating Engines",
  "Service Worker",
  "Travis CI",
  "Unit Testing",
  "HeadLess Browser Testing",
  "TDD",
  "Elastic Search",
  "elixir basics"
];

console.log(langs.length);
